{{- if  .Values.ui.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: ui
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: ui
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if .Values.ssl.enabled }}
    acme.cert-manager.io/http01-edit-in-place: "true"
    {{- end }}
spec:
  {{- if .Values.ssl.enabled }}
  tls:
  - hosts:
    - {{ .Values.cloudDomain }}
    secretName: {{ .Values.ssl.secretName.cloud }}
  {{- end }}
  rules:
  - host: {{ .Values.cloudDomain }}
    http:
      paths:
      - backend:
          service:
            name: ui
            port:
              number: 80
        path: /
        pathType: Prefix
{{- end }}