{{- if  .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: ui
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: ui
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      labels:
        app: ui
    spec:
      priorityClassName: {{ .Values.priorityClass.modelz }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      containers:
      - name:  ui
        resources:
          {{- .Values.ui.resources | toYaml | nindent 12 }}
        image: {{ .Values.ui.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        livenessProbe:
          {{- if $.Values.ui.livenessProbe }}
          initialDelaySeconds: {{ $.Values.ui.livenessProbe.initialDelaySeconds | default 0 }}
          periodSeconds: {{ $.Values.ui.livenessProbe.periodSeconds | default 10 }}
          timeoutSeconds: {{ $.Values.ui.livenessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ $.Values.ui.livenessProbe.failureThreshold | default 3 }}
          successThreshold: {{ $.Values.ui.livenessProbe.successThreshold | default 1 }}
          {{- end }}
          httpGet:
            path: /
            port: 80
        readinessProbe:
          {{- if $.Values.ui.readinessProbe }}
          initialDelaySeconds: {{ $.Values.ui.readinessProbe.initialDelaySeconds | default 0 }}
          periodSeconds: {{ $.Values.ui.readinessProbe.periodSeconds | default 10 }}
          timeoutSeconds: {{ $.Values.ui.readinessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ $.Values.ui.readinessProbe.failureThreshold | default 3 }}
          successThreshold: {{ $.Values.ui.readinessProbe.successThreshold | default 1 }}
          {{- end }}
          httpGet:
            path: /
            port: 80
        env:
        - name: VITE_SUPABASE_URL
          value: {{ .Values.ui.supabaseUrl | quote }}
        - name: VITE_SUPABASE_ANON_KEY
          value: {{ .Values.ui.supabaseAnonKey | quote }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
