{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: ui
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: http
  selector:
    app: ui
{{- end }}
