kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bubble-autoscaler
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: bubble-autoscaler
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["replicationcontrollers/scale"]
    verbs: ["get", "update"]
  - apiGroups: ["extensions","apps"]
    resources: ["deployments/scale", "replicasets/scale"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update", "create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bubble-autoscaler
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: bubble-autoscaler
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bubble-autoscaler
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: bubble-autoscaler
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: bubble-autoscaler
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: bubble-autoscaler
  apiGroup: rbac.authorization.k8s.io
