{{ $config := pick .Values.bubble.gpuT4Config "ladder" "linear" }}
{{ if not $config }}
{{ fail "A config must be supplied for either ladder mode or linear mode" }}
{{- end }}
{{- if and $config.ladder $config.linear }}
{{ fail "You must supply a config for either ladder mode or linear mode but not both" }}
{{- end }}
{{ $key := mustFirst (keys $config) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.priorityClass.bubbleCPU }}-autoscaler
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.priorityClass.bubbleCPU }}-autoscaler
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{ $key }}: |-
    {{- get $config $key | mustToJson | nindent 4 }}
