{{- if  .Values.defaultHTTPBackend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: default-http-backend
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: default-http-backend
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-http-backend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      labels:
        app: default-http-backend
    spec:
      priorityClassName: {{ .Values.priorityClass.modelz }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      containers:
      - name:  default-http-backend
        resources:
          {{- .Values.defaultHTTPBackend.resources | toYaml | nindent 12 }}
        image: {{ .Values.defaultHTTPBackend.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
          - "/usr/bin/backend"
          {{- if .Values.debug }}
          - "--debug"
          {{- end }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          {{- if $.Values.defaultHTTPBackend.livenessProbe }}
          initialDelaySeconds: {{ $.Values.defaultHTTPBackend.livenessProbe.initialDelaySeconds | default 0 }}
          periodSeconds: {{ $.Values.defaultHTTPBackend.livenessProbe.periodSeconds | default 10 }}
          timeoutSeconds: {{ $.Values.defaultHTTPBackend.livenessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ $.Values.defaultHTTPBackend.livenessProbe.failureThreshold | default 3 }}
          successThreshold: {{ $.Values.defaultHTTPBackend.livenessProbe.successThreshold | default 1 }}
          {{- end }}
          httpGet:
            path: /ping
            port: 8080
        readinessProbe:
          {{- if $.Values.defaultHTTPBackend.readinessProbe }}
          initialDelaySeconds: {{ $.Values.defaultHTTPBackend.readinessProbe.initialDelaySeconds | default 0 }}
          periodSeconds: {{ $.Values.defaultHTTPBackend.readinessProbe.periodSeconds | default 10 }}
          timeoutSeconds: {{ $.Values.defaultHTTPBackend.readinessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ $.Values.defaultHTTPBackend.readinessProbe.failureThreshold | default 3 }}
          successThreshold: {{ $.Values.defaultHTTPBackend.readinessProbe.successThreshold | default 1 }}
          {{- end }}
          httpGet:
            path: /ping
            port: 8080
        env:
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
