{{- if  .Values.gatus.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: gatus
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: gatus
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if .Values.ssl.enabled }}
    acme.cert-manager.io/http01-edit-in-place: "true"
    {{- end }}
spec:
  {{- if .Values.ssl.enabled }}
  tls:
  - hosts:
    - {{ .Values.gatus.domain }}
    secretName: {{ .Values.ssl.secretName.status }}
  {{- end }}
  rules:
  - host: {{ .Values.gatus.domain }}
    http:
      paths:
      - backend:
          service:
            name: gatus
            port:
              number: 8080
        path: /
        pathType: Prefix
{{- end }}
