{{- if  .Values.gatus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: gatus
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: gatus
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      name: gatus
      namespace: {{ .Release.Namespace | quote }}
      labels:
        app: gatus
    spec:
      serviceAccountName: gatus
      terminationGracePeriodSeconds: 5
      containers:
        - image: {{ .Values.gatus.image }}
          imagePullPolicy: IfNotPresent
          name: gatus
          env:
            - name: GATUS_CONFIG_PATH
              value: {{ .Values.gatus.configDir }}/gatus.yaml
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            {{- .Values.gatus.resources | toYaml | nindent 12 }}
          livenessProbe:
            {{- if $.Values.gatus.livenessProbe }}
            initialDelaySeconds: {{ $.Values.gatus.livenessProbe.initialDelaySeconds | default 0 }}
            periodSeconds: {{ $.Values.gatus.livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ $.Values.gatus.livenessProbe.timeoutSeconds | default 5 }}
            failureThreshold: {{ $.Values.gatus.livenessProbe.failureThreshold | default 3 }}
            successThreshold: {{ $.Values.gatus.livenessProbe.successThreshold | default 1 }}
            {{- end }}
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            {{- if $.Values.gatus.readinessProbe }}
            initialDelaySeconds: {{ $.Values.gatus.readinessProbe.initialDelaySeconds | default 0 }}
            periodSeconds: {{ $.Values.gatus.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ $.Values.gatus.readinessProbe.timeoutSeconds | default 5 }}
            failureThreshold: {{ $.Values.gatus.readinessProbe.failureThreshold | default 3 }}
            successThreshold: {{ $.Values.gatus.readinessProbe.successThreshold | default 1 }}
            {{- end }}
            httpGet:
              path: /health
              port: 8080
          volumeMounts:
            - mountPath: {{ .Values.gatus.configDir }}/gatus.yaml
              name: gatus-config
              subPath: gatus.yaml
      volumes:
        - name: gatus-config
          configMap:
            name: gatus-config
            items:
              - key: gatus.yaml
                path: gatus.yaml
                mode: 0644
{{- end }}