{{- if  .Values.gatus.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: gatus
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: gatus
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gatus
{{- end }}