{{- if  .Values.gatus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: gatus-config
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: gatus-config
  namespace: {{ .Release.Namespace | quote }}
data:
  gatus.yaml: |
    metrics: true
    security:
      basic:
        username: {{ .Values.gatus.username }}
        password-bcrypt-base64: {{ .Values.gatus.password }}
    alerting:
      discord:
        webhook-url: {{ .Values.gatus.discordWebHook }}
      default-alert:
        enabled: {{ .Values.gatus.discordAlert }}
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 3
    endpoints:
      - name: gateway
        group: core
        url: http://gateway.{{ .Release.Namespace }}:8080/system/info
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - has([BODY].version) == true
{{- if .Values.apiserver.enabled }}
      - name: apiserver
        group: core
        url: http://apiserver.{{ .Release.Namespace }}:8080/api/v1/server_resources
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - has([BODY].version) == true
{{- end }}
{{- if  .Values.autoscaler.enabled }}
      - name: autoscaler
        group: core
        url: http://autoscaler.{{ .Release.Namespace }}:8080/system/info
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - has([BODY].version) == true
{{- end }}

      - name: buildkitd
        group: internal
        url: tcp://buildkitd.{{ .Release.Namespace }}:1234
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
{{- if .Values.hfserver.enabled }}
      - name: hfserver
        group: internal
        url: http://hfserver.{{ .Release.Namespace }}:8080/
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - has([BODY].version) == true
{{- end }}

{{- if .Values.apiserver.enabled }}
      - name: ui
        group: frontend
        url: http://ui.{{ .Release.Namespace }}:80/
        interval: 5m
        conditions:
          - "[STATUS] == 200"
{{- end }}
{{- if .Values.prometheus.enabled }}
      - name: prometheus
        group: frontend
        url: http://prometheus.{{ .Release.Namespace }}:9090/
        interval: 5m
        conditions:
          - "[STATUS] == 200"
{{- end }}
{{- end }}