{{- if .Values.dcgm.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-nvidia-dcgm-exporter
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: nvidia-dcgm-exporter
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  template:
    metadata:
      labels:
        app: nvidia-dcgm-exporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.dcgm.cloudAccelerateNodeAffinityKey }}
                operator: Exists
      tolerations:
      - operator: "Exists"
      volumes:   
      - name: nvidia-dcgm-exporter-metrics
        configMap:
          name: nvidia-dcgm-exporter-metrics    
      - name: nvidia-install-dir-host
        hostPath:
          path: /home/kubernetes/bin/nvidia           
      - name: pod-resources
        hostPath:
            path: /var/lib/kubelet/pod-resources              
      containers:
      - name: nvidia-dcgm-exporter  
        image: {{ .Values.dcgm.exporter.image.repository }}:{{ .Values.dcgm.exporter.image.tag }}
        imagePullPolicy: {{ .Values.dcgm.exporter.image.pullPolicy }}
        command: ["/bin/bash", "-c"]
        args: 
        - hostname $NODE_NAME; dcgm-exporter -k --remote-hostengine-info $(NODE_IP) --collectors /etc/dcgm-exporter/counters.csv --collect-interval 20000
        ports:
        - name: metrics
          containerPort: {{ .Values.dcgm.exporter.containerPort }}
        securityContext:
          privileged: true          
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: "DCGM_EXPORTER_KUBERNETES_GPU_ID_TYPE"
          value: "device-name"              
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: nvidia-dcgm-exporter-metrics
          mountPath: "/etc/dcgm-exporter"
          readOnly: true
        - name: nvidia-install-dir-host
          mountPath: /usr/local/nvidia
        - name: pod-resources
          mountPath: /var/lib/kubelet/pod-resources 
{{- end }}