{{- if .Values.dcgm.enabled }}
kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{ template "modelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: nvidia-dcgm-exporter
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: nvidia-dcgm-exporter
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.dcgm.exporter.containerPort | quote }}
spec:
  selector:
    app: nvidia-dcgm-exporter
  ports:
  - name: "metrics"
    port: {{ .Values.dcgm.exporter.containerPort }}
{{- end }}
